services:
  ids:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: ["eth0"]        #  paramètre d'interface
    volumes:
      - ./logs:/usr/src/app/logs      #  pour récupérer ids.log après arrêt
    restart: unless-stopped   #  optionnel, redémarre si le conteneur crashe